baseline: This site will contain blogs written by me and will all be copyleft
  for you to do whatever you want with it.
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
description: This site will contain blogs written by me and will all be copyleft
  for you to do whatever you want with it.
date:
  format: j F Y
  timezone: Asia/Kolkata
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Gats Personal Blog
baseurl: /
canonicalurl: true
